language: julia
os:
    - linux
julia:
    - 1
    - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
after_success:
    - julia -e 'import Pkg; cd(Pkg.dir("Qumulants")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
